export const GET_USERS_SUCCESS_ACTION = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE_ACTION = 'GET_USERS_FAILURE'

export const GET_PRODUCTS_SUCCESS_ACTION = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE_ACTION = 'GET_PRODUCTS_FAILURE'

export const GET_CART_SUCCESS_ACTION = 'GET_CART_SUCCESS'
export const GET_CART_FAILURE_ACTION = 'GET_CART_FAILURE'

export const GET_WISHLIST_SUCCESS_ACTION = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAILURE_ACTION = 'GET_WISHLIST_FAILURE'